/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.1.0")
    testImplementation("org.slf4j:slf4j-reload4j:2.0.12")


    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    runtimeOnly("androidx.core:core-ktx:1.12.0")


    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("commons-lang:commons-lang:2.2")
    implementation("xerces:xercesImpl:2.8.1")
    implementation("joda-time:joda-time:2.12.5")
    implementation("com.google.protobuf:protobuf-java:3.25.3")


}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
