name: GradleWorkflow

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout project sources
        uses: actions/checkout@v4
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # - name: Downloading UA Client
      #   run: |
      #     echo "Downloading the UA"
      #     curl -LJ "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar" -o "UA.jar"

      # - name: Verifying the UA scanner
      #   run: |
      #     echo "Verifying the UA"
      #     java -jar "UA.jar" -v
      
      - name: Downloading CLI Client
        run: |
          echo "Downloading the CLI"
          curl "https://downloads.mend.io/cli/linux_amd64/mend" -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
          ls

      - name: Downloading CLI Self Contained
        run: |
          echo "Downloading the CLI SC"
          curl https://downloads.mend.io/cli-standalone/mend_linux_amd64.tgz -o /usr/local/bin/mend_linux_amd64.tgz && tar -xzvf /usr/local/bin/mend_linux_amd64.tgz && chmod +x ./mend-linux-amd64/mend
          ls
          export MEND_INSTALL_DIR=/usr/local/bin/mend-linux-amd64/bin
     
      # - name: Verify Scanner
      #   run: |
      #     echo "Verifying the CLI"
      #     mend version
      
      # - name: Scan with UA
      #   env:
      #     WS_GRADLE_INCLUDEMODULES: app
      #     WS_GRADLE_INCLUDEDCONFIGURATIONS: runtimeClasspath  && chmod +x /usr/local/bin/mend-linux-amd64/mend
      #     WS_GRADLE_RESOLVEDEPENDENCIES: true
      #     WS_APIKEY: ${{ secrets.EUAPI }}
      #     WS_USERKEY: ${{ secrets.EU_USER_KEY }}
      #     WS_WSS_URL: ${{ secrets.EU_URL }}
      #     WS_PRODUCTNAME: Homework3
      #     WS_PROJECTNAME: UAGradleWrapperAllAlerts
      #     WS_LOG_LEVEL: DEBUG
      #   run: java -jar UA.jar

      - name: Scan with SC CLI
        env:
          MEND_URL: ${{ secrets.MEND_URL }}
          MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
          MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
          MEND_LOG_LEVEL: DEBUG
        run: |
          ./mend-linux-amd64/mend sca --local
        continue-on-error: true
      
      - name: Scan with CLI
        env:
          MEND_URL: ${{ secrets.MEND_URL }}
          MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
          MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
          MEND_LOG_LEVEL: DEBUG
        run: |
          mend dep --update --scope "Homework3//CLIGradleWrapper" --non-interactive -e
        continue-on-error: true
      
      - name: Printing CLI logs
        run: cat ~/.mend/logs/sca/*
